---
creation_rules:
  - path_regex: (controlplane|worker)\.yaml
    encrypted_regex: ^(secret|bootstraptoken|secretboxEncryptionSecret|token|key|password)$
    age: age1sa224kdq8x9qvne5nhcgn074xtkcytvn9nje6sjm0rhs5p5lr59svncpgu

  - path_regex: secrets.yaml
    encrypted_regex: ^(secret|bootstraptoken|secretboxencryptionsecret|token|key)$
    age: age1sa224kdq8x9qvne5nhcgn074xtkcytvn9nje6sjm0rhs5p5lr59svncpgu

  - path_regex: talosconfig
    encrypted_regex: ^key$
    age: age1sa224kdq8x9qvne5nhcgn074xtkcytvn9nje6sjm0rhs5p5lr59svncpgu

  - path_regex: kubeconfig
    encrypted_regex: ^client-key-data$
    age: age1sa224kdq8x9qvne5nhcgn074xtkcytvn9nje6sjm0rhs5p5lr59svncpgu

stores:
  yaml:
    indent: 2
